### ISSUE TITLE
zmq.error.ZMQError: Address already in use

### ISSUE THREAD

**Issue by badkey** [emacs-jupyter/jupyter#471]
When calling the babel environment
`
SRC jupyter-python :session bad :kernel Py310
print("org babel")
#+END_SRC
`
the following error encounters
`
Executing Jupyter-Python unknown at position 190806...
Launching py310 kernel...
jupyter--start-kernel-process: Kernel process exited:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jbatke/.virtualenv/Py310/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/home/jbatke/.virtualenv/Py310/lib/python3.10/site-packages/traitlets/config/application.py", line 1042, in launch_instance
    app.initialize(argv)
  File "/home/jbatke/.virtualenv/Py310/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/home/jbatke/.virtualenv/Py310/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 678, in initialize
    self.init_sockets()
  File "/home/jbatke/.virtualenv/Py310/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 317, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/jbatke/.virtualenv/Py310/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 252, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/home/jbatke/.virtualenv/Py310/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 228, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/home/jbatke/.virtualenv/Py310/lib/python3.10/site-packages/zmq/sugar/socket.py", line 300, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

Process jupyter-kernel-py310 exited abnormally with code 1
`

How can I debug that? I have no clue to start (I updraded the virtual env which apparantly did not help). Any hint is welcome.
I use emacs 28.2 and emacs-jupyter from melpa.

**Comment by badkey** [comment]
In the meantime I found 
`(setq jupyter-use-zmq nil) `
avoids the problem.
